#!/bin/bash

build() {
    local mod

    add_binary "gpg"
    add_binary "gpg-agent"
    add_binary "pinentry-tty"
    add_binary "pcscd"
    add_binary "/usr/lib/gnupg/scdaemon"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows to use gnupg to decrypt multiple files.

Options (fetched from the kernel command line):
* gpg_decrypt=FSTYPE:encryptedfilepath:decryptedfilepath
* gpg_import=FSTYPE:gpg-key

Notes:
* FSTYPE: can be 'rootfs' for the current intramfs
* decryptedfilepath: will be in the current initramfs
* Multiple files can be provided using ';' as a separator

Example:
gpg_decrypt=rootfs:/etc/keyfile.gpg:/tmp/keyfile;ext2:/dev/sda1:/encryptedkey:/etc/decryptedkey gpg_import=rootfs:/etc/public.asc
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
