#!/bin/bash

# This file is part of mkinitcpio-gnupg.
#
# mkinitcpio-gnupg is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# mkinitcpio-gnupg is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with mkinitcpio-gnupg.  If not, see <https://www.gnu.org/licenses/>.

build() {
    local mod

    add_binary "gpg"
    add_binary "gpg-agent"
    add_binary "pinentry-tty"
    add_binary "pcscd"
    add_binary "/usr/lib/gnupg/scdaemon"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows to use gnupg to decrypt multiple files.

Options (fetched from the kernel command line):
* gpg_decrypt=FSTYPE:encryptedfilepath:decryptedfilepath
* gpg_import=FSTYPE:gpg-key

Notes:
* FSTYPE: can be 'rootfs' for the current intramfs
* decryptedfilepath: will be in the current initramfs
* Multiple files can be provided using ';' as a separator

Example:
gpg_decrypt=rootfs:/etc/keyfile.gpg:/tmp/keyfile;ext2:/dev/sda1:/encryptedkey:/etc/decryptedkey gpg_import=rootfs:/etc/public.asc
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
